import webpackAliases from "./webpackAliases";
import {
  walletDataReducer,
  listenToWalletData,
  INITIALIZE,
  UPDATE_WALLET_DATA,
  stateMiddleware,
  storageMiddleware,
} from "./reduxHelpers";
import ModuleWrapper from "./ModuleWrapper";
import browserslistQuery from "./browserslistQuery";

// This package could be imported by other environments other than on Nexus Wallet, such as babel.config.js
// where NEXUS global variable is not defined. So we have to prepare for that with default values
const {
  walletVersion,
  components: {
    GlobalStyles,
    ThemeController,
    Icon,
    Panel,
    AutoSuggest,
    FieldSet,
    Switch,
    Modal,
    Tooltip,
    Select,
    TextField,
    FormField,
    Arrow,
    HorizontalTab,
    VerticalTab,
    Button,
    Dropdown,
  } = {},
  utilities: {
    color,
    copyToClipboard,
    send,
    showNotification,
    showErrorDialog,
    showSuccessDialog,
    showInfoDialog,
    rpcCall,
    apiCall,
    secureApiCall,
    proxyRequest,
    confirm,
    updateState,
    updateStorage,
    onceInitialize,
    onWalletDataUpdated,
    openInBrowser,
  } = {},
} = global.NEXUS || {};

export {
  walletVersion,
  // Components
  GlobalStyles,
  ThemeController,
  Icon,
  Panel,
  AutoSuggest,
  FieldSet,
  Switch,
  Modal,
  Tooltip,
  Select,
  TextField,
  FormField,
  Arrow,
  HorizontalTab,
  VerticalTab,
  Button,
  Dropdown,
  // Utilities
  color,
  copyToClipboard,
  send,
  showNotification,
  showErrorDialog,
  showSuccessDialog,
  showInfoDialog,
  rpcCall,
  apiCall,
  secureApiCall,
  proxyRequest,
  confirm,
  updateState,
  updateStorage,
  onceInitialize,
  onWalletDataUpdated,
  openInBrowser,
  // Helpers
  webpackAliases,
  browserslistQuery,
  walletDataReducer,
  listenToWalletData,
  INITIALIZE,
  UPDATE_WALLET_DATA,
  stateMiddleware,
  storageMiddleware,
  ModuleWrapper,
};
